#pragma once

#include <ymir/core/types.hpp>

#include <cmrc/cmrc.hpp>
CMRC_DECLARE(ymir_core_shaders);

#include <array>

namespace ymir::vdp {

// ---------------------------------------------------------------------------------------------------------------------
// Shaders

/// @brief Name of the entrypoint function for all compute shaders.
inline constexpr const char *kCSEntrypoint = "CSMain";

/// @brief Contains the compiled shader files from res/shaders/src.
inline cmrc::embedded_filesystem g_fsShaders = cmrc::ymir_core_shaders::get_filesystem();

// ---------------------------------------------------------------------------------------------------------------------
// Basic types

using HLSLbool = uint32; // bools align to 4 bytes
using HLSLint = sint32;
using HLSLuint = uint32;

struct alignas(HLSLuint) ColorR8G8B8A8 {
    uint8 r, g, b, a;
};
static_assert(sizeof(ColorR8G8B8A8) == sizeof(uint32));

union HLSLuint2 {
    std::array<HLSLuint, 2> array;
    struct {
        HLSLuint x, y;
    };
    struct {
        HLSLuint r, g;
    };
};
static_assert(sizeof(HLSLuint2) == sizeof(HLSLuint) * 2);

union HLSLuint3 {
    std::array<HLSLuint, 3> array;
    struct {
        HLSLuint x, y, z;
    };
    struct {
        HLSLuint r, g, b;
    };
};
static_assert(sizeof(HLSLuint3) == sizeof(HLSLuint) * 3);

union HLSLuint4 {
    std::array<HLSLuint, 4> array;
    struct {
        HLSLuint x, y, z, w;
    };
    struct {
        HLSLuint r, g, b, a;
    };
};
static_assert(sizeof(HLSLuint4) == sizeof(HLSLuint) * 4);

union HLSLint2 {
    std::array<HLSLint, 2> array;
    struct {
        HLSLint x, y;
    };
    struct {
        HLSLint r, g;
    };
};
static_assert(sizeof(HLSLint2) == sizeof(HLSLint) * 2);

union HLSLint3 {
    std::array<HLSLint, 3> array;
    struct {
        HLSLint x, y, z;
    };
    struct {
        HLSLint r, g, b;
    };
};
static_assert(sizeof(HLSLint3) == sizeof(HLSLint) * 3);

// =====================================================================================================================
// Common rendering parameters

struct EnhancementsParams {
    HLSLuint deinterlace : 1;           //     0  Deinterlace
    HLSLuint transparentMeshes : 1;     //     1  Render mesh sprites as transparent
    HLSLuint : 4;                       //   2-5  (reserved)
    HLSLuint scaleResolution : 1;       //     6  Scale internal resolution
    HLSLuint scaleResTargetWidth : 13;  //  7-19  Target internal resolution width   (x + 1)
    HLSLuint scaleResTargetHeight : 12; // 20-31  Target internal resolution height  (y + 1)
};
static_assert(sizeof(EnhancementsParams) == sizeof(HLSLuint));

// =====================================================================================================================
// VDP1 rendering
//
// The VDP1 rendering pipeline is submitted at least once per framebuffer swap if any drawing operations were submitted
// in the frame.
//
// VDP1 erase dispatched done only once per swap.
// Each VDP1 command is dispatched individually, sometimes multiple times depending on the number of spans generated by
// the polygon.
// CPU writes to FBRAM are handled at swap time, immediately before span submissions and at swap. CPU reads from FBRAM
// force a synchronization point (fence wait) for the most recent VDP1 frame.
//
// Root 32-bit constants hold renderer parameters shared across all VDP1 compute shaders such as relevant registers and
// active enhancements, as well as per-shader parameters.

/// @brief Common VDP1 rendering parameters shared by all shaders.
struct alignas(16) VDP1CommonRenderParams {
    struct DisplayParams {                 //  bits  use
        HLSLuint fbSizeH : 1;              //     0  Framebuffer horizontal size shift    (512 << x)
        HLSLuint fbSizeV : 1;              //     1  Framebuffer vertical size shift      (256 << x)
        HLSLuint pixel8Bits : 1;           //     2  Pixel data size                      0=16 bits; 1=8 bits
        HLSLuint doubleDensity : 1;        //     3  Double-density interlace mode
        HLSLuint dblInterlaceEnable : 1;   //     4  Double interlace enable
        HLSLuint dblInterlaceDrawLine : 1; //     5  Double interlace line                0=even; 1=odd
        HLSLuint evenOddCoordSelect : 1;   //     6  Even/odd coordinate select (HSS)     0=even; 1=odd
        HLSLuint drawFB : 1;               //     7  Current draw framebuffer index
        HLSLuint hresMode : 3;             //  8-10  Horizontal resolution mode (VDP2 TVMD.HRESO2-0)
        HLSLuint vresMode : 2;             // 11-12  Vertical resolution mode   (VDP2 TVMD.VRESO1-0)
    } displayParams;
    static_assert(sizeof(DisplayParams) == sizeof(HLSLuint));

    EnhancementsParams enhancements;
};

/// @brief VDP1 erase parameters, appended to common rendering parameters in the erase shader.
struct alignas(16) VDP1EraseParams {
    struct Coords {          //  bits  use
        HLSLuint x1 : 6;     //   0-5  Erase X1 (left) coordinate (x << 3)
        HLSLuint y1 : 9;     //  6-14  Erase Y1 (top) coordinate
        HLSLuint x3 : 7;     // 15-21  Erase X3 (right) coordinate (x << 3)
        HLSLuint y3 : 9;     // 22-30  Erase Y3 (bottom) coordinate
        HLSLuint scaleV : 1; //    31  Erase Y coordinate shift
    } coords;
    static_assert(sizeof(Coords) == sizeof(HLSLuint));

    struct Erase {                 //  bits  use
        HLSLuint writeValue : 16;  //  0-15  Erase write value
        HLSLuint addressShift : 1; //    16  Erase address shift (coordY << (x + 8))
    } erase;

    struct VBlankEraseParams { //  bits  use
        HLSLuint enable : 1;   //     0  VBlank erase active
        HLSLuint maxY : 9;     //   1-9  Last VBlank erase line
        HLSLuint maxX : 10;    // 10-19  Last VBlank erase pixel in line
    } vblank;
    static_assert(sizeof(VBlankEraseParams) == sizeof(HLSLuint));
};

/// @brief VDP1 polygon drawing parameters, appended to common rendering parameters in the polygon drawing shader.
struct alignas(16) VDP1PolyDrawParams {
    HLSLuint numSpans; // Number of spans in the list
};

/// @brief VDP1 span drawing parameters.
struct VDP1SpanParams {
    HLSLint2 coord0;        // Starting coordinates
    HLSLint2 coord1;        // Ending coordinates
    HLSLuint skip : 16;     // Initial skip steps
    HLSLuint cmdIndex : 16; // Command parameters index

    struct Attributes {             //  bits  use
        HLSLuint antialias : 1;     //     0  Antialias line
        HLSLuint textured : 1;      //     1  Textured polygon
        HLSLuint flipH : 1;         //     2  Horizontal flip
                                    // --- texture only ---
        HLSLuint texV : 10;         //  3-12  Texture V coordinate
        HLSLuint endCodeIndex : 10; // 13-22  U coordinate of the second end code
    } attrs;
    static_assert(sizeof(Attributes) == sizeof(HLSLuint));

    // Gouraud only parameters
    HLSLuint3 gouraud0; // Starting gouraud value
    HLSLuint3 gouraud1; // Ending gouraud value
};

/// @brief VDP1 command parameters. Referenced by spans.
struct VDP1CommandParams {
    struct SysClip {     //  bits  use
        HLSLuint h : 16; //  0-15  System clipping area width
        HLSLuint v : 16; // 16-31  System clipping area height
    } sysClip;
    static_assert(sizeof(SysClip) == sizeof(HLSLuint));

    struct UserClip {    //  bits  use
        HLSLuint x : 16; //  0-15  User clipping area horizontal coordinate
        HLSLuint y : 16; // 16-31  User clipping area vertical coordinate
    };
    static_assert(sizeof(UserClip) == sizeof(HLSLuint));
    UserClip userClip0; // User clipping area top-left coordinate
    UserClip userClip1; // User clipping area bottom-right coordinate

    HLSLuint cmdpmod : 16; // CMDPMOD value
    HLSLuint cmdcolr : 16; // CMDCOLR value
    HLSLuint cmdsize : 16; // CMDSIZE value (textured only)
    HLSLuint cmdsrca : 16; // CMDSRCA value (textured only)
};

/// @brief A fragment used by the order-independent transparency algorithm.
struct VDP1OITFragment {
    HLSLuint data;
    HLSLuint next;
};

/// @brief An FBRAM write entry.
struct VDP1FBRAMWrite {
    HLSLuint address;
    HLSLuint andMask;
    HLSLuint orMask;
};

/// @brief Maximum number of spans to send per batch.
inline constexpr uint32 kMaxVDP1Spans = 65535;

/// @brief Maximum number of commands to send per batch.
inline constexpr uint32 kMaxVDP1Commands = 4096;

/// @brief Maximum number of non-OIT fragments per dispatch.
inline constexpr uint32 kMaxVDP1FragmentsPerDispatch = 4194240;

/// @brief Maximum number of OIT fragments per dispatch.
inline constexpr uint32 kMaxVDP1OITFragmentsPerDispatch = 524288;

// The polygon drawing shader uses the span index as a sequence number to enable parallel drawing.
// This sequence has to fit in the top 16 bits of the output value, limiting the number of span drawn per dispatch.
// We reserve zero as a special value indicating the previous dispatch's contents (or empty pixels).
// Therefore, the absolute maximum number of spans that can be submitted per dispatch is 65535.
static_assert(kMaxVDP1Spans <= 65535);

// The command index is a 16-bit number packed into one of the VDP1 spans fields.
static_assert(kMaxVDP1Commands <= 65535);

// The absolute maximum limit for pixels per dispatch is dictated by the maximum number of compute dispatch groups.
// Each group has 64 threads, as defined in the polygon drawing shader.
static_assert(kMaxVDP1FragmentsPerDispatch <= 65535 * 64);
static_assert(kMaxVDP1OITFragmentsPerDispatch <= 65535 * 64);

/// @brief Base Xst, Yst, KA for params A and B for a given line.
struct alignas(16) VDP2RotParamBase {
    uint32 tableAddress;
    sint32 Xst, Yst;
    uint32 KA;
};
static_assert(sizeof(VDP2RotParamBase) == sizeof(uint32) * 4);

// =====================================================================================================================
// VDP2 rendering
//
// The VDP2 rendering pipeline is invoked at least once per frame. When VRAM, CRAM and/or register writes happen, the
// renderer processes scanlines up to the previous VCNT and commits all changes before proceeding.
//
// Since the VDP2 rendering process has no visible effect on the rest of the Saturn's components, there is no need for
// additional synchronization constraints on memory and register reads or writes. The VDP2 state is handled by the VDP
// controller and the renderer maintains a local independent copy of the VRAM, CRAM and VDP2 registers for fully
// asynchronous rendering.
//
// Root 32-bit constants hold renderer parameters shared across all VDP2 compute shaders such as the starting line for
// continuation of work interrupted by state changes, relevant registers and active enhancements.

/// @brief Common VDP2 rendering parameters shared by all shaders.
struct VDP2CommonRenderParams {
    // Top Y coordinate of target rendering area.
    HLSLuint startY;

    struct DisplayParams {                 //  bits  use
        HLSLuint displayEnable : 1;        //     0  Display enabled
                                           //          0 = display off
                                           //          1 = display on
        HLSLuint borderColorMode : 1;      //     1  Border color mode
                                           //          0 = black
                                           //          1 = back screen color
        HLSLuint interlaceMode : 2;        //   2-3  Interlace mode
                                           //          0 = progressive
                                           //          1 = invalid
                                           //          2 = single-density interlace
                                           //          3 = double-density interlace
        HLSLuint oddField : 1;             //     4  Field
                                           //          0 = even
                                           //          1 = odd
        HLSLuint exclusiveMonitor : 1;     //     5  Exclusive monitor mode
                                           //          0 = normal
                                           //          1 = exclusive
        HLSLuint colorRAMMode : 2;         //   6-7  Color RAM mode
                                           //          0 = RGB 5:5:5, 1024 words
                                           //          1 = RGB 5:5:5, 2048 words
                                           //          2 = RGB 8:8:8, 1024 words
                                           //          3 = RGB 8:8:8, 1024 words  (same as mode 2, undocumented)
        HLSLuint hiResH : 1;               //     8  Horizontal resolution
                                           //          0 = 320/352
                                           //          1 = 640/704
        HLSLuint palMode : 1;              //     9  Display standard (VDP2 TVSTAT.PAL)
                                           //          0 = NTSC
                                           //          1 = PAL
        HLSLuint hresMode : 3;             // 10-12  Horizontal resolution mode (VDP2 TVMD.HRESO2-0)
        HLSLuint vresMode : 2;             // 13-14  Vertical resolution mode   (VDP2 TVMD.VRESO1-0)
        HLSLuint dblInterlaceEnable : 1;   //    15  VDP1 double interlace enable flag (VDP1 FBCR.DIE)
        HLSLuint dblInterlaceDrawLine : 1; //    16  VDP1 double interlace draw line   (VDP1 FBCR.DIL)
    } displayParams;
    static_assert(sizeof(DisplayParams) == sizeof(HLSLuint));

    struct LayerParams {                   //  bits  use
        HLSLuint layerEnabled : 6;         //   0-5  Layer enable state based on BGON and other factors:
                                           //        bit  RBG0+RBG1   RBG0        RBG1        no RBGs
                                           //          0  Sprite      Sprite      Sprite      Sprite
                                           //          1  RBG0        RBG0        -           -
                                           //          2  RBG1        NBG0        RBG1        NBG0
                                           //          3  EXBG        NBG1/EXBG   NBG1/EXBG   NBG1/EXBG
                                           //          4  -           NBG2        NBG2        NBG2
                                           //          5  -           NBG3        NBG3        NBG3
        HLSLuint bgEnabled : 6;            //  6-11  Individual layer enable flags
                                           //        bit  layer
                                           //          8  NBG0
                                           //          9  NBG1
                                           //         10  NBG2
                                           //         11  NBG3
                                           //         12  RBG0
                                           //         13  RBG1
        HLSLuint lineColorEnableRBG0 : 1;  //    12  Line color screen enable for RBG0
        HLSLuint lineColorEnableRBG1 : 1;  //    13  Line color screen enable for RBG1
        HLSLuint mosaicH : 4;              // 14-17  Horizontal mosaic size (minus one)
        HLSLuint mosaicV : 4;              // 18-21  Vertical mosaic size (minus one)
        HLSLuint rotParamMode : 2;         // 22-23  Rotation parameter mode
                                           //          0 = always use A
                                           //          1 = always use B
                                           //          2 = select based on coefficient data
                                           //          3 = select based on window flag
        HLSLuint restrictedColorCalc : 1;  //    24  Restricted color calculations
        HLSLuint extendedColorCalc : 1;    //    25  Use extended color calculation
                                           //        (always disabled in hi-res modes)
        HLSLuint useAdditiveBlend : 1;     //    26  Blend mode
                                           //          0 = alpha
                                           //          1 = additive
        HLSLuint useSecondScreenRatio : 1; //    27  Use second screen ratio
        HLSLuint colorGradEnable : 1;      //    28  Color gradation enabled
        HLSLuint colorGradScreen : 3;      // 29-31  Color gradation screen
                                           //          0  Sprite
                                           //          1  RBG0
                                           //          2  NBG0/RBG1
                                           //          3  (invalid)
                                           //          4  NBG1/EXBG
                                           //          5  NBG2
                                           //          6  NBG3
                                           //          7  (invalid)
    } layerParams;
    static_assert(sizeof(LayerParams) == sizeof(HLSLuint));

    struct RotParams {                       //  bits  use
        HLSLuint coeffTableCRAM : 1;         //     0  Coefficient table location
                                             //          0 = VRAM
                                             //          1 = CRAM
        HLSLuint coeffDataAccess : 4;        //   1-4  Coefficient data access for VRAM banks:
                                             //         bit  bank
                                             //           0  A0/A
                                             //           1  A1
                                             //           2  B0/B
                                             //           3  B1
        HLSLuint coeffDataPerDot : 1;        //     5  Per-dot coefficients
                                             //          false = per line
                                             //          true  = per dot
                                             // ------------------------------------------------
        HLSLuint coeffATableEnable : 1;      //     6  Coefficient table A enabled
        HLSLuint coeffADataSize : 1;         //     7  Coefficient A data size
                                             //          0 = 2 words
                                             //          1 = 1 word
        HLSLuint coeffADataMode : 2;         //   8-9  Coefficient A data mode
                                             //          0 = kx/ky
                                             //          1 = kx
                                             //          2 = ky
                                             //          3 = Px
        HLSLuint coeffAUseLineColorData : 1; //    10  Use coefficient A line color data
                                             // ------------------------------------------------
        HLSLuint coeffBTableEnable : 1;      //    11  Coefficient table B enabled
        HLSLuint coeffBDataSize : 1;         //    12  Coefficient B data size
                                             //          0 = 2 words
                                             //          1 = 1 word
        HLSLuint coeffBDataMode : 2;         // 13-14  Coefficient B data mode
                                             //          0 = kx/ky
                                             //          1 = kx
                                             //          2 = ky
                                             //          3 = Px
        HLSLuint coeffBUseLineColorData : 1; //    15  Use coefficient B line color data
    } rotParams;
    static_assert(sizeof(RotParams) == sizeof(HLSLuint));

    struct SpriteParams {             //  bits  use
        HLSLuint rotate : 1;          //     0  Sprite layer rotation
                                      //          0 = normal
                                      //          1 = use rotation parameter A
        HLSLuint pixel8Bits : 1;      //     1  VDP1 data size
                                      //          0 = 16-bit
                                      //          1 = 8-bit
        HLSLuint type : 4;            //   2-5  Sprite data type
        HLSLuint fbSizeH : 1;         //     6  VDP1 framebuffer horizontal size shift  (512 << x)
        HLSLuint fbSizeV : 1;         //     7  VDP1 framebuffer vertical size shift    (256 << x)
        HLSLuint inHalfResH : 1;      //     8  Sprite input at half resolution
        HLSLuint outHalfResH : 1;     //     9  Sprite output at half resolution
        HLSLuint mixedFormat : 1;     //    10  Sprite layer color format
                                      //          0 = palette only
                                      //          1 = mixed palette/RGB
        HLSLuint colorCalcEnable : 1; //    11  Sprite color calculation enable
        HLSLuint colorCalcValue : 3;  // 12-14  Sprite target color calculation value
        HLSLuint colorCalcCond : 2;   // 15-16  Special color calculation condition
        HLSLuint colorDataOffset : 3; // 17-19  Special color data offset in CRAM
        HLSLuint useSpriteWindow : 1; //    20  Use sprite window
        HLSLuint windowEnabled : 1;   //    21  Sprite window enabled for the sprite layer
        HLSLuint windowInverted : 1;  //    22  Sprite window inverted for the sprite layer
        HLSLuint displayFB : 1;       //    23  Current sprite display framebuffer index
    } spriteParams;
    static_assert(sizeof(SpriteParams) == sizeof(HLSLuint));

    // Packed 8x 3-bit sprite priorities + 5-bit color calculation ratios
    HLSLuint2 spritePriosRatios;

    struct VCellScroll {            //  bits  use
        HLSLuint tableAddress : 19; //  0-18  Vertical cell scroll table address
        HLSLuint inc : 3;           // 19-21  Vertical cell scroll address increment per cell  (x << 2)
    } vcellScroll;
    static_assert(sizeof(VCellScroll) == sizeof(HLSLuint));

    struct Windows {                       //  bits  use
        HLSLuint spriteWindowLogic : 1;    //     0  Sprite window logic        0=OR; 1=AND
        HLSLuint spriteW0Enable : 1;       //     1  Sprite W0 enable           0=disable; 1=enable
        HLSLuint spriteW0Invert : 1;       //     2  Sprite W0 invert           0=disable; 1=enable
        HLSLuint spriteW1Enable : 1;       //     3  Sprite W1 enable           0=disable; 1=enable
        HLSLuint spriteW1Invert : 1;       //     4  Sprite W1 invert           0=disable; 1=enable
        HLSLuint colorCalcWindowLogic : 1; //     5  Color calc. window logic   0=OR; 1=AND
        HLSLuint colorCalcW0Enable : 1;    //     6  Color calc. W0 enable      0=disable; 1=enable
        HLSLuint colorCalcW0Invert : 1;    //     7  Color calc. W0 invert      0=disable; 1=enable
        HLSLuint colorCalcW1Enable : 1;    //     8  Color calc. W1 enable      0=disable; 1=enable
        HLSLuint colorCalcW1Invert : 1;    //     9  Color calc. W1 invert      0=disable; 1=enable
        HLSLuint colorCalcSWEnable : 1;    //    10  Color calc. SW enable      0=disable; 1=enable
        HLSLuint colorCalcSWInvert : 1;    //    11  Color calc. SW invert      0=disable; 1=enable
    } windows;
    static_assert(sizeof(Windows) == sizeof(HLSLuint));

    EnhancementsParams enhancements;
};

/// @brief Global VDP2 window parameters.
struct VDP2GlobalWindowParams {
    // Top-left coordinates
    HLSLuint2 start;

    // Bottom-right coordinates
    HLSLuint2 end;

    // Base address of the line window table
    HLSLuint lineWindowTableAddress;

    // Whether to use the line window table
    HLSLbool lineWindowTableEnable;
};

/// @brief Per-layer VDP2 window parameters.
struct VDP2LayerWindowParams {
    // Window logic
    //   false = OR
    //   true = AND
    HLSLbool windowLogicAnd;

    // Window 0 enable
    HLSLbool window0Enable;

    // Window 0 invert
    HLSLbool window0Invert;

    // Window 1 enable
    HLSLbool window1Enable;

    // Window 1 invert
    HLSLbool window1Invert;
};

/// @brief VDP2 extended window parameters (includes sprite window).
struct VDP2LayerWindowParamsS {
    VDP2LayerWindowParams base;

    // Sprite window enable
    HLSLbool spriteWindowEnable;

    // Sprite window invert
    HLSLbool spriteWindowInvert;
};

/// @brief Base VDP2 layer rendering parameters, common to NBGs and RBGs.
struct VDP2BaseBGParams {
    // Background enabled
    HLSLbool enabled;

    // If true, honor transparency bit in color data.
    // Derived from BGON.xxTPON
    HLSLbool enableTransparency;

    // Whether the background uses cells (false) or a bitmap (true).
    // Derived from CHCTLA/CHCTLB.xxBMEN
    HLSLbool bitmap;

    // Priority number from 0 (transparent) to 7 (highest).
    // Derived from PRINA/PRINB/PRIR.xxPRINn
    HLSLuint priorityNumber;

    // Special priority mode.
    // Derived from SFPRMD.xxSPRMn
    HLSLuint priorityMode;

    // Special function select (0=A, 1=B).
    // Derived from SFSEL.xxSFCS
    HLSLuint specialFunctionSelect;

    // Cell size shift corresponding to the dimensions of a character pattern (0=1x1, 1=2x2).
    // Derived from CHCTLA/CHCTLB.xxCHSZ
    HLSLuint cellSizeShift;

    // Character color format.
    // Derived from CHCTLA/CHCTLB.xxCHCNn
    HLSLuint colorFormat;

    // Color RAM base offset.
    // Derived from CRAOFA/CRAOFB.xxCAOSn
    HLSLuint cramOffset;

    // Supplementary bits 4-0 for scroll screen character number, when using 1-word characters.
    // Derived from PNCNn/PNCR.xxSCNn
    HLSLuint supplScrollCharNum;

    // Supplementary bits 6-4 for palette number.
    // Used with scroll screen when using 1-word characters, or with bitmap screens.
    // The value is already shifted in place to optimize rendering calculations.
    // Derived from PNCNn/PNCR.xxSPLTn (scroll) or BMPNA/BMPNB.xxBMPn (bitmap)
    HLSLuint supplPalNum;

    // Supplementary special color calculation bit.
    // Derived from PNCNn/PNCR.xxSCC (scroll) or BMPNA/BMPNB.xxBMCC (bitmap)
    HLSLuint supplSpecialColorCalc;

    // Supplementary special priority bit.
    // Derived from PNCNn/PNCR.xxSPR (scroll) or BMPNA/BMPNB.xxBMPR (bitmap)
    HLSLuint supplSpecialPriority;

    // Enables the mosaic effect.
    // If vertical cell scroll is also enabled, the mosaic effect is bypassed.
    // Derived from MZCTL.xxMZE
    HLSLbool mosaicEnable;

    // Enables color calculation.
    // Derived from CCCTL.xxCCEN
    HLSLbool colorCalcEnable;

    // Character number width: 10 bits (false) or 12 bits (true).
    // When true, disables the horizontal and vertical flip bits in the character.
    // Derived from PNCNn/PNCR.xxCNSM
    HLSLbool extChar;

    // Whether characters use one (false) or two (true) words.
    // Derived from PNCNn/PNCR.xxPNB
    HLSLbool twoWordChar;

    // Whether pattern name data is accessible for each VRAM bank (bits 0 to 3: A0, A1, B0, B1).
    // Derived from CYCxn, RAMCTL and BGON (for RBG0/1 restrictions to NBGs)
    HLSLuint patNameAccess;

    // Whether character pattern data is accessible for each VRAM bank (bits 0 to 3: A0, A1, B0, B1).
    // Derived from CYCxn, RAMCTL and BGON (for RBG0/1 restrictions to NBGs)
    HLSLuint charPatAccess;

    // Whether accesses to character pattern data for this background is delayed per bank due to illegal VRAM access
    // patterns (bits 0 to 3: A0, A1, B0, B1). Derived from CYCxn, RAMCTL, ZMCTL and CHCTLA/CHCTLB.xxCHSZ
    HLSLuint charPatDelay;

    // Address offset for VRAM data for this background on each VRAM bank caused by illegal VRAM access patterns
    // (bits 0 to 3: A0, A1, B0, B1). Derived from CYCxn, RAMCTL and ZMCTL
    HLSLuint vramDataOffset;

    // Special color calculation mode.
    // Derived from SFCCMD.xxSCCMn
    HLSLuint specialColorCalcMode;

    // Page shifts are either 0 or 1, used when determining which plane a particular (x,y) coordinate belongs to.
    // A shift of 0 corresponds to 1 page per plane dimension.
    // A shift of 1 corresponds to 2 pages per plane dimension.
    // Derived from PLSZ.xxPLSZn
    HLSLuint2 pageShift;

    // Bitmap dimensions, when the screen is in bitmap mode.
    // Derived from CHCTLA/CHCTLB.xxBMSZ
    HLSLuint2 bitmapSize;

    // Base address of bitmap data.
    // Derived from MPOFN (NBG0-3) or MPOFR (RotParam A-B)
    HLSLuint bitmapBaseAddress;

    // Window parameters
    VDP2LayerWindowParamsS windowParams;
};

/// @brief VDP2 NBG layer rendering parameters.
struct NBGParams {
    VDP2BaseBGParams base;

    // Screen scroll amount, in 11.8 fixed-point format.
    // Used in scroll NBGs.
    // Scroll amounts for NBGs 2 and 3 do not have a fractional part, but the values are still stored with 8 fractional
    // bits here for consistency and ease of implementation.
    // Derived from SCXINn and SCXDNn
    HLSLuint2 scrollAmount;

    // Screen scroll increment per pixel, in 11.8 fixed-point format.
    // NBGs 2 and 3 do not have increment registers; they always increment each coordinate by 1.0, which is stored here
    // for consistency and ease of implementation.
    // Derived from ZMXINn and ZMXDNn
    HLSLuint2 scrollInc;

    // Page base addresses for NBG planes A-D.
    // Derived from MPOFN, MPABNn, MPCDNn, CHCTLA/CHCTLB.xxCHSZ, PNCNn.xxPNB and PLSZ.xxPLSZn
    std::array<HLSLuint, 4> pageBaseAddresses;

    // Whether to use the vertical cell scroll table in VRAM.
    // Only valid for NBG0 and NBG1.
    // Derived from SCRCTL.NnVCSC
    HLSLbool vcellScrollEnable;

    // Whether to use the horizontal line scroll table in VRAM.
    // Only valid for NBG0 and NBG1.
    // Derived from SCRCTL.NnLSCX
    HLSLbool lineScrollXEnable;

    // Whether to use the vertical line scroll table in VRAM.
    // Only valid for NBG0 and NBG1.
    // Derived from SCRCTL.NnLSCY
    HLSLbool lineScrollYEnable;

    // Whether to use horizontal line zoom/scaling.
    // Only valid for NBG0 and NBG1.
    // Derived from SCRCTL.NnLZMX
    HLSLbool lineZoomEnable;

    // Line scroll table interval shift. The interval is calculated as (1 << lineScrollInterval).
    // Only valid for NBG0 and NBG1.
    // Derived from SCRCTL.NnLSS1-0
    HLSLuint lineScrollInterval;

    // Line scroll table base address.
    // Only valid for NBG0 and NBG1.
    // Derived from LSTAnU/L
    HLSLuint lineScrollTableAddress;

    // Vertical cell scroll offset.
    // Only valid for NBG0 and NBG1.
    // Based on CYCA0/A1/B0/B1 parameters.
    HLSLuint vcellScrollOffset;

    // Is the vertical cell scroll read delayed by one cycle?
    // Only valid for NBG0 and NBG1.
    // Based on CYCA0/A1/B0/B1 parameters.
    HLSLuint vcellScrollDelay;

    // Is the first vertical cell scroll entry repeated?
    // Only valid for NBG0.
    // Based on CYCA0/A1/B0/B1 parameters.
    HLSLuint vcellScrollRepeat;
};

/// @brief VDP2 RBG layer rendering parameters.
struct RBGParams {
    VDP2BaseBGParams base;

    // Rotation BG screen-over process.
    // Derived from PLSZ.RxOVRn
    HLSLuint screenOverProcess;

    // Screen-over pattern name value.
    // Derived from OVPNRA/B
    HLSLuint screenOverPatternName;

    /// @brief Page base addresses for RBG planes A-P using Rotation Parameters A and B.
    /// Indexing: [RotParam A/B][Plane A-P]
    /// Derived from `mapIndices`, `CHCTLA/CHCTLB.xxCHSZ`, `PNCR.xxPNB` and `PLSZ.xxPLSZn`.
    std::array<std::array<HLSLuint, 16>, 2> pageBaseAddresses;
};

/// @brief LNCL/BACK screen parameters.
struct VDP2LineBackScreenParams {
    // Base address of color data
    HLSLuint baseAddress;

    // Use colors per line
    //   false = per screen
    //   true  = per line
    HLSLbool perLine;
};

/// @brief VDP2 layer rendering parameters.
struct VDP2LayerRenderParams {
    NBGParams nbg[4];
    RBGParams rbg[2];

    VDP2GlobalWindowParams windows[2];

    VDP2LayerWindowParams rotWindows;

    VDP2LineBackScreenParams lineScreenParams;
    VDP2LineBackScreenParams backScreenParams;

    // Bit-packed special function code flags.
    //  bits  use
    //   0-7  Special function code A
    //  8-15  Special function code B
    HLSLuint specialFunctionCodes;
};

/// @brief VDP2 compositor parameters.
struct VDP2ComposeParams {
    // Use color calculation per layer (0=disable; 1=enable)
    //   bit  layer
    //     0  Sprite
    //     1  RBG0
    //     2  RBG1/NBG0
    //     3  NBG1/EXBG
    //     4  NBG2
    //     5  NBG3
    //     6  Back screen
    //     7  Line screen
    HLSLuint colorCalcEnable;

    // Color offset enable per layer (0=disable; 1=enable)
    //   bit  layer
    //     0  Sprite
    //     1  RBG0
    //     2  RBG1/NBG0
    //     3  NBG1/EXBG
    //     4  NBG2
    //     5  NBG3
    //     6  Back screen
    HLSLuint colorOffsetEnable;

    // Color offset select per layer (0=A; 1=B)
    //   bit  layer
    //     0  Sprite
    //     1  RBG0
    //     2  RBG1/NBG0
    //     3  NBG1/EXBG
    //     4  NBG2
    //     5  NBG3
    //     6  Back screen
    HLSLuint colorOffsetSelect;

    // Line color enable per layer (0=disable; 1=enable)
    //   bit  layer
    //     0  Sprite
    //     1  RBG0
    //     2  RBG1/NBG0
    //     3  NBG1/EXBG
    //     4  NBG2
    //     5  NBG3
    //     6  Back screen (always false to simplify shader implementation)
    HLSLuint lineColorEnable;

    // Color offset A (RGB999)
    HLSLint3 colorOffsetA;

    // Color offset B (RGB999)
    HLSLint3 colorOffsetB;

    // NBG/RBG color calculation ratios
    // index  layer
    //     0  RBG0
    //     1  NBG0/RBG1
    //     2  NBG1/EXBG
    //     3  NBG2
    //     4  NBG3
    std::array<HLSLuint, 5> bgColorCalcRatios;

    // Back/line screen color calculation ratios
    // index  layer
    //     0  Back screen
    //     1  Line screen
    std::array<HLSLuint, 2> backLineColorCalcRatios;
};

/// @brief Number of entries in the VDP2 CRAM color cache.
/// VDP2 CRAM can have at most 2048 colors (in mode 1 - RGB 5:5:5 with access to full CRAM).
inline constexpr size_t kVDP2CRAMColorCacheEntries = kVDP2CRAMSize / sizeof(uint16);

/// @brief VDP2 CRAM converted color cache array.
using CRAMColorCache = std::array<ColorR8G8B8A8, kVDP2CRAMColorCacheEntries>;

/// @brief Size of the VDP2 CRAM color buffer, in bytes.
inline constexpr UINT kVDP2CRAMColorBufferSize = sizeof(CRAMColorCache);

/// @brief Size of the VDP2 CRAM rotation coefficients buffer, in bytes.
/// The second half of CRAM can be used for that purpose.
inline constexpr UINT kVDP2CRAMRotCoeffBufferSize = kVDP2CRAMSize / 2;

} // namespace ymir::vdp
