name: CI build

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

permissions:
  packages: write
  contents: read

env:
  USERNAME: ymir-emu
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/ymir-emu/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/ymir-emu/index.json,readwrite"
  VULKAN_SDK_VERSION: "1.4.357.0"

jobs:
  build-windows:
    name: windows-${{ matrix.arch.name }}-${{ matrix.build-set.name }}
    runs-on: ${{ matrix.arch.runner }}

    strategy:
      fail-fast: false

      matrix:
        arch:
          - name: x64
            runner: windows-2025
            vcpkg_triplet: x64-win-llvm-static-md
          - name: a64
            runner: windows-11-arm
            vcpkg_triplet: arm64-windows
        build-set:
          - name: full
            library-only: "no"
          - name: libonly
            library-only: "yes"

    steps:
      # Set up MASM for lzma
      - name: Set up MASM
        uses: glslang/setup-masm@bd171b9b0a619ff6237c164fab5fb920cc579889
        if: ${{ matrix.arch.name == 'x64' }}

      - name: Set up Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@37effcfa045411f8bfbbda26df2fd1b3bf3436fa
        with:
          vulkan_version: ${{ env.VULKAN_SDK_VERSION }}
          cache: true

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Bootstrap vcpkg
        if: ${{ matrix.build-set.library-only == 'no' }}
        shell: pwsh
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat

      - name: Add NuGet sources to vcpkg
        if: ${{ matrix.build-set.library-only == 'no' }}
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: Configure CMake
        shell: pwsh
        env:
          CXX: clang++
          CC: clang
        run: |
          if ("${{ matrix.build-set.library-only }}" -eq "no") {
            cmake -B ${{ steps.strings.outputs.build-output-dir }} `
              -DVCPKG_TARGET_TRIPLET=${{ matrix.arch.vcpkg_triplet }} `
              -DCMAKE_CXX_COMPILER=clang++ `
              -DCMAKE_C_COMPILER=clang `
              -DCMAKE_BUILD_TYPE=Debug `
              -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
              -DBUILD_SHARED_LIBS=OFF `
              -DYmir_ENABLE_DEVLOG=OFF `
              -DYmir_ENABLE_IMGUI_DEMO=OFF `
              -DYmir_ENABLE_UPDATE_CHECKS=ON `
              -DYmir_ENABLE_SANDBOX=OFF `
              -DYmir_ENABLE_YMDASM=ON `
              -DYmir_ENABLE_IPO=OFF `
              -DYmir_LIBRARY_ONLY=OFF `
              -S ${{ github.workspace }} `
              -G Ninja
          } else {
            cmake -B ${{ steps.strings.outputs.build-output-dir }} `
              -DCMAKE_CXX_COMPILER=clang++ `
              -DCMAKE_C_COMPILER=clang `
              -DCMAKE_BUILD_TYPE=Debug `
              -DBUILD_SHARED_LIBS=OFF `
              -DYmir_ENABLE_DEVLOG=OFF `
              -DYmir_ENABLE_IPO=OFF `
              -DYmir_LIBRARY_ONLY=ON `
              -S ${{ github.workspace }} `
              -G Ninja
          }

      - name: Build
        env:
          CXX: clang++
          CC: clang
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel

  build-linux:
    name: linux-${{ matrix.arch.name }}-${{ matrix.build-set.name }}
    runs-on: ${{ matrix.arch.runner }}

    strategy:
      fail-fast: false

      matrix:
        arch:
          - name: x64
            runner: ubuntu-24.04
          - name: a64
            runner: ubuntu-24.04-arm
        build-set:
          - name: full
            library-only: "no"
          - name: libonly
            library-only: "yes"

    steps:
      - name: Cache Vulkan SDK with DXC build (AArch64)
        if: matrix.arch.name == 'a64'
        id: cache-dxc
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/vulkan-sdk/${{ env.VULKAN_SDK_VERSION }}
          key: dxc-aarch64-${{ runner.os }}-${{ env.VULKAN_SDK_VERSION }}

      - name: Set up Vulkan SDK
        id: vulkan-sdk
        if: steps.cache-dxc.outputs.cache-hit != 'true'
        uses: jakoch/install-vulkan-sdk-action@37effcfa045411f8bfbbda26df2fd1b3bf3436fa
        with:
          vulkan_version: ${{ env.VULKAN_SDK_VERSION }}
          cache: true

      - name: Build DXC for Vulkan SDK (AArch64)
        if: matrix.arch.name == 'a64' && steps.cache-dxc.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd $VULKAN_SDK/..
          ./vulkansdk --skip-deps --maxjobs dxc

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make pkg-config \
            cmake ninja-build gnome-desktop-testing \
            libasound2-dev libpulse-dev libaudio-dev \
            libjack-dev libsndio-dev libx11-dev \
            libxext-dev libxrandr-dev libxcursor-dev \
            libxfixes-dev libxi-dev libxss-dev \
            libxtst-dev libxkbcommon-dev libdrm-dev \
            libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev \
            libudev-dev mono-complete libltdl-dev clang-18 \
            autoconf autoconf-archive automake

      - name: Bootstrap vcpkg
        if: ${{ matrix.build-set.library-only == 'no' }}
        shell: bash
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Cache vcpkg
        if: ${{ matrix.build-set.library-only == 'no' }}
        id: cache-vcpkg
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: linux-${{ matrix.arch.name }}-vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'vcpkg-triplets/**') }}

      - name: Configure CMake
        env:
          VCPKG_BINARY_SOURCES: 'clear;files,${{ github.workspace }}/vcpkg_cache,readwrite'
        run: |
          if [ ${{ matrix.build-set.library-only}} = 'no' ]; then
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=clang++-18 \
              -DCMAKE_C_COMPILER=clang-18 \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DBUILD_SHARED_LIBS=OFF \
              -DYmir_ENABLE_DEVLOG=OFF \
              -DYmir_ENABLE_IMGUI_DEMO=OFF \
              -DYmir_ENABLE_UPDATE_CHECKS=ON \
              -DYmir_ENABLE_SANDBOX=OFF \
              -DYmir_ENABLE_YMDASM=ON \
              -DYmir_ENABLE_IPO=OFF \
              -DYmir_LIBRARY_ONLY=OFF \
              -S ${{ github.workspace }} \
              -G Ninja
          else
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=clang++-18 \
              -DCMAKE_C_COMPILER=clang-18 \
              -DCMAKE_BUILD_TYPE=Debug \
              -DBUILD_SHARED_LIBS=OFF \
              -DYmir_ENABLE_DEVLOG=OFF \
              -DYmir_ENABLE_IPO=OFF \
              -DYmir_LIBRARY_ONLY=ON \
              -S ${{ github.workspace }} \
              -G Ninja
          fi

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel

  build-freebsd:
    name: freebsd-${{ matrix.arch.name }}-${{ matrix.build-set.name }}
    runs-on: ${{ matrix.arch.runner }}

    strategy:
      fail-fast: false

      matrix:
        arch:
          - name: x64
            runner: ubuntu-24.04
          # - name: arm64
          #   runner: ubuntu-24.04
        build-set:
          - name: full
            library-only: "no"
          - name: libonly
            library-only: "yes"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      # TODO: configure vcpkg cache

      - uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524
        env:
          CXX: clang++21
          CC: clang21
        with:
          operating_system: freebsd
          architecture: ${{ matrix.arch.name }}
          version: '15.0'
          environment_variables: CXX CC
          run: |
            sudo pkg upgrade -y
            sudo pkg install -y cmake evdev-proto git gmake libX11 libXcursor libXext \
              libXfixes libXi libXrandr libXrender libXScrnSaver libXtst libglvnd \
              libinotify llvm21 ninja patchelf pkgconf python3 vulkan-loader zip \
              glslang shaderc vulkan-headers dxc

            if [ ${{ matrix.build-set.library-only}} = 'no' ]; then
              ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

              cmake -B ${{ steps.strings.outputs.build-output-dir }} \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DBUILD_SHARED_LIBS=OFF \
                -DYmir_ENABLE_DEVLOG=OFF \
                -DYmir_ENABLE_IMGUI_DEMO=OFF \
                -DYmir_ENABLE_UPDATE_CHECKS=ON \
                -DYmir_ENABLE_SANDBOX=OFF \
                -DYmir_ENABLE_YMDASM=ON \
                -DYmir_ENABLE_IPO=OFF \
                -DYmir_LIBRARY_ONLY=OFF \
                -S ${{ github.workspace }} \
                -G Ninja
            else
              cmake -B ${{ steps.strings.outputs.build-output-dir }} \
                -DCMAKE_BUILD_TYPE=Debug \
                -DBUILD_SHARED_LIBS=OFF \
                -DYmir_ENABLE_DEVLOG=OFF \
                -DYmir_ENABLE_IPO=OFF \
                -DYmir_LIBRARY_ONLY=ON \
                -S ${{ github.workspace }} \
                -G Ninja
            fi

            cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel

  build-macos:
    name: macos-${{ matrix.arch.name }}-${{ matrix.build-set.name }}
    runs-on: macos-latest

    strategy:
      fail-fast: false

      matrix:
        arch:
          - name: "x64"
            isa_name: "x86_64"
            triplet_arch: "x64"
          - name: "arm64"
            isa_name: "arm64"
            triplet_arch: "arm64"
          # Disabled because vcpkg doesn't support universal binaries
          # See https://github.com/microsoft/vcpkg/discussions/19454
          #- name: "universal"
          #  isa_name: "'x86_64;arm64'"
        build-set:
          - name: full
            library-only: "no"
          - name: libonly
            library-only: "yes"

    steps:
      - name: Set up Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@37effcfa045411f8bfbbda26df2fd1b3bf3436fa
        with:
          vulkan_version: ${{ env.VULKAN_SDK_VERSION }}
          cache: true
          stripdown: true

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install tools
        shell: bash
        run: brew install mono nuget

      - name: Bootstrap vcpkg
        if: ${{ matrix.build-set.library-only == 'no' }}
        shell: bash
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Add NuGet sources to vcpkg
        if: ${{ matrix.build-set.library-only == 'no' }}
        shell: bash
        run: |
          nuget sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          nuget setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"

      - name: Configure CMake
        run: |
          if [ ${{ matrix.build-set.library-only}} = 'no' ]; then
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DBUILD_SHARED_LIBS=OFF \
              -DYmir_ENABLE_DEVLOG=OFF \
              -DYmir_ENABLE_IMGUI_DEMO=OFF \
              -DYmir_ENABLE_UPDATE_CHECKS=ON \
              -DYmir_ENABLE_SANDBOX=OFF \
              -DYmir_ENABLE_YMDASM=ON \
              -DYmir_ENABLE_IPO=OFF \
              -DYmir_LIBRARY_ONLY=OFF \
              -S ${{ github.workspace }} \
              -G Ninja
          else
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_BUILD_TYPE=Debug \
              -DBUILD_SHARED_LIBS=OFF \
              -DYmir_ENABLE_DEVLOG=OFF \
              -DYmir_ENABLE_IPO=OFF \
              -DYmir_LIBRARY_ONLY=ON \
              -S ${{ github.workspace }} \
              -G Ninja
          fi

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel
